 version: '2'
 services:
   Dynamexil:
     build: ./Dynamexil
     devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
     depends_on:
      - redis
     restart: always
     ports: 
      - "80:5000"
     networks:
      - back-tire
   redis:
     build: ./redis
     networks:
      - back-tire
 networks:
  back-tire:
    driver: bridge